# Generated by Django 3.0 on 2020-01-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('view_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('collection_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('main_photo_path', models.CharField(max_length=128, null=True, verbose_name='主图路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Article_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type_name', models.CharField(max_length=32, verbose_name='板块类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central_name', models.CharField(max_length=32, verbose_name='地区名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Jc_html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_id', models.CharField(max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=32, verbose_name='登录账号')),
                ('login_passwd', models.CharField(max_length=64, verbose_name='登录密码')),
                ('name', models.CharField(default=None, max_length=32, null=True, verbose_name='用户昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('integral', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='积分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provices_name', models.CharField(max_length=32, verbose_name='省份、直辖市名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('central', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cen_province', to='jcshare.Central', verbose_name='地区外键')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2048, verbose_name='评论正文')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('father_comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jcshare.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_com', to='jcshare.User')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('col_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_user', to='jcshare.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='col_user', to='jcshare.User')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=32, verbose_name='城市、直辖市区名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('provinces', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_city', to='jcshare.Provinces', verbose_name='省份外键')),
            ],
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('att_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_ed_user', to='jcshare.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_user', to='jcshare.User')),
            ],
        ),
        migrations.CreateModel(
            name='article_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(max_length=256, null=True, verbose_name='图片path')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='jcshare.Article', verbose_name='帖子图片外键')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acticle_type', to='jcshare.Article_type', verbose_name='article外键关联类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='jcshare.City', verbose_name='市、直辖市区'),
        ),
        migrations.AddField(
            model_name='article',
            name='provinces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to='jcshare.Provinces', verbose_name='省份、直辖市'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_user', to='jcshare.User', verbose_name='用户外键'),
        ),
    ]
